services:
  backend:
    image: python:3.9-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app  
      # Monte toute la racine du projet dans /app
      # Assure-toi que le dossier backend est bien monté
    command: ["python", "citations.py"]
    networks:
      - app-network
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html  # Assure-toi que le fichier index.html est monté
      - ./nginx.conf:/etc/nginx/nginx.conf  # Utilise le fichier de config personnalisé
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge
