
services:
  backend:
    build: ./backend
    container_name: backend
    working_dir: /app
    networks:
      - app-network
    ports:
      - "5000:5000"
    restart: always  # Permet de redémarrer en cas d'erreur

  frontend:
    image: nginx:alpine
    container_name: frontend
    depends_on:
      - backend  # Attend que le backend soit prêt
    volumes:
      - ./frontend:/usr/share/nginx/html  # Assure-toi que le fichier index.html est monté
      - ./nginx.conf:/etc/nginx/nginx.conf  # Utilise le fichier de config personnalisé
    networks:
      - app-network
    ports:
      - "80:80"
    restart: always  # Permet de redémarrer en cas d'erreur

networks:
  app-network:
#    driver: bridge
