# Image leger Python
FROM python:3.9-alpine

# Définir un répertoire/dossiers de travail
WORKDIR /app

# Copier le fichier requirements.txt et installer les bibliothèques tout en supprimant les caques des paquets téléchargée
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code source
COPY . .

# Lancer l'application
CMD ["python", "citations.py"]
